{{- if and (hasKey .Values.public_env_variables "CGW_DB_TLS") (eq .Values.public_env_variables.CGW_DB_TLS "yes") }}
  {{- if not (or .Values.db_cert .Values.existingDBCertsSecret) }}
    {{- fail "Either db_cert or existingDBCertsSecret must be set when CGW_DB_TLS is 'yes'." }}
  {{- end }}
{{- end }}

{{- if and (not .Values.existingDBCertsSecret) (hasKey .Values.public_env_variables "CGW_DB_TLS") (eq .Values.public_env_variables.CGW_DB_TLS "yes") }}
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: {{ include "cgw.name" . }}
    helm.sh/chart: {{ include "cgw.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "cgw.fullname" . }}-db-cert
kind: Secret
type: Opaque
data:
  cert.pem: {{ .Values.db_cert | b64enc | quote }}
{{- end}}
