{{- if not (or .Values.secret_env_variables .Values.existingEnvSecret) }}
{{- fail "Either secret_env_variables or existingEnvSecret must be set." }}
{{- end }}

{{- if not (.Values.existingEnvSecret) }}
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: {{ include "cgw.name" . }}
    helm.sh/chart: {{ include "cgw.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "cgw.fullname" . }}-env
kind: Secret
type: Opaque
data:
  # Secret env variables
  {{- range $key, $value := .Values.secret_env_variables }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end}}
