apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: etcd3
  name: etcd3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etcd3
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -c
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/patroni-demo: "true"
        io.kompose.service: etcd3
    spec:
      containers:
        - args:
            - etcd
            - --name
            - etcd3
            - --initial-advertise-peer-urls
            - http://etcd3:2380
          env:
            - name: ETCD_INITIAL_CLUSTER
              value: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: new
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: tutorial
            - name: ETCD_LISTEN_CLIENT_URLS
              value: http://0.0.0.0:2379
            - name: ETCD_LISTEN_PEER_URLS
              value: http://0.0.0.0:2380
            - name: ETCD_UNSUPPORTED_ARCH
              value: arm64
          image: harbor.io.optimcloud.com/optimcloud/patroni:latest
          name: demo-etcd3
          ports:
            - containerPort: 2379
              protocol: TCP
            - containerPort: 2380
              protocol: TCP
      hostname: etcd3
      restartPolicy: Always
