apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: patroni3
  name: patroni3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: patroni3
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -c
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/patroni-demo: "true"
        io.kompose.service: patroni3
    spec:
      containers:
        - env:
            - name: ETCDCTL_ENDPOINTS
              value: http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
            - name: PATRONI_ETCD3_HOSTS
              value: '''etcd1:2379'',''etcd2:2379'',''etcd3:2379'''
            - name: PATRONI_NAME
              value: patroni3
            - name: PATRONI_REPLICATION_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PATRONI_REPLICATION_PASSWORD
                  name: patroni-env
            - name: PATRONI_REPLICATION_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: PATRONI_REPLICATION_USERNAME
                  name: patroni-env
            - name: PATRONI_RESTAPI_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PATRONI_RESTAPI_PASSWORD
                  name: patroni-env
            - name: PATRONI_RESTAPI_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: PATRONI_RESTAPI_USERNAME
                  name: patroni-env
            - name: PATRONI_SCOPE
              value: demo
            - name: PATRONI_SUPERUSER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PATRONI_SUPERUSER_PASSWORD
                  name: patroni-env
            - name: PATRONI_SUPERUSER_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: PATRONI_SUPERUSER_USERNAME
                  name: patroni-env
            - name: PATRONI_admin_OPTIONS
              valueFrom:
                configMapKeyRef:
                  key: PATRONI_admin_OPTIONS
                  name: patroni-env
            - name: PATRONI_admin_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PATRONI_admin_PASSWORD
                  name: patroni-env
          image: harbor.io.optimcloud.com/optimcloud/patroni:latest
          name: demo-patroni3
          ports:
            - containerPort: 5432
              protocol: TCP
      hostname: patroni3
      restartPolicy: Always
